# Change these first
owner: civcicd # Your GitHub organization or username, where this repository lives
repo: uptime-monitor-commercial # The name of this repository

sites:
  - name: Sparc
    url: https://sparc.concorde2000.com
  - name: Concorde2000
    url: https://www.concorde2000.com
  - name: Concorde Help 
    url: https://engage.concorde2000.com
  - name: Customer Support
    url: https://customercare.concorde2000.com
  - name: Drivers Clearinghouse
    url: https://www.driversclearinghouse.com
  - name: FastTest
    url: https://fasttest.concorde2000.com/Login.aspx
  - name: Smart
    url: https://smart.concorde2000.com
  - name: Concorde Admissions
    url: https://concordeadmissions.com
  - name: Concorde Analytics
    url: https://concordeanalytics.com
  - name: AppCheck
    url: https://www09.8f7.com
  - name: AF E-Opto Api
    url: https://af-e-opto-web-app-serv-api-01.azurewebsites.us
  - name: AF E-Opto Frontend
    url: https://af-e-opto-web-app-serv-client-01.azurewebsites.us
  - name: AF Quick Errors Api
    url: https://af-qk-errors-serv-api-01.azurewebsites.us
  - name: AF Quick Errors Frontend
    url: https://af-qk-errors-web-app-serv-client-01.azurewebsites.us
  - name: AF Password Reset Api
    url: https://af-passwd-reset-app-serv-api-01.azurewebsites.us
  - name: AF Password Reset Frontend
    url: https://af-passwd-reset-web-app-client-01.azurewebsites.us


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.concorde2000.com
  # baseUrl: /uptime-monitor-commercial
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a monitor and status page for the following sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
